version: '3'

services:
  terraria:
    image: beardedio/terraria:vanilla-latest
    ports:
      - '7777:7777'
    restart: unless-stopped
    environment:
      - world=<Oonga_Boonga>
    volumes:
      - /home/ubuntu/terraria/config:/config
    tty: true