version: '3'

services:
  terraria:
    image: beardedio/terraria:vanilla-latest
    ports:
      - '7777:7777'
    environment:
      - world=<Oonga_Boonga>
    volumes:
      - /home/ubuntu/terraria/config:/config
    tty: true
    command: tail -f /dev/null
