version: '3.3'

services:
  terraria:
    image: beardedio/terraria:vanilla-latest
    environment:
      world=Oonga_Boona
    volumes:
      - ./Worlds:/config
    ports:
      - "7777:7777"
    restart: always